apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
  labels:
    jenkins/agent: "true"
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: jenkins-agent
      image: bitnami/jenkins-agent:latest
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - |
                curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                chmod +x kubectl
                mv kubectl /usr/local/bin/
                curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
  restartPolicy: Never
