apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
  labels:
    jenkins/agent: "true"
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--skip-tls-verify=true"
        - "--single-snapshot"
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
        - name: workspace
          mountPath: /workspace
    - name: tools
      image: bitnami/kubectl:latest
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: workspace
          mountPath: /workspace
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - |
                curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-credentials
        items:
          - key: .dockerconfigjson
            path: config.json

    - name: workspace
      emptyDir: {}
  restartPolicy: Never
