apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
    - port: {{ .Values.flask.servicePort }}
      targetPort: {{ .Values.flask.containerPort }}
      protocol: TCP
